### ISSUE TITLE
Argument for SEARCH_FIRST_X_SECONDS_FOR_CAPTION_LINE

### ISSUE THREAD

**Issue by philsalv** [amiaopensource/sccyou#7]
Many videos in our collection have long introductions, logos, etc., without caption data before the main video content. These last longer than 20 seconds, so sccyou doesn't see captions. It would be useful to have an argument for how long to look for caption data.

I don't have much coding or any Git experience, so I'm not sure how to present this, but I cobbled something together. It doesn't check if the argument is a positive integer, but it's a start:

Edit at line 121:
`while getopts ":t:hsy" OPT ; do`

Inserted at line 123:
`        t) SEARCH_FIRST_X_SECONDS_FOR_CAPTION_LINE=$OPTARG ;;`

**Comment by dericed** [comment]
Good point, this should be an option. Or possibly it's better to probe the middle x seconds of the video rather than the beginning.

**Comment by philsalv** [comment]
Searching in the middle is a good idea! That cuts out the need for the argument.

**Comment by MHGT120** [comment]
I tried out sccyou again today, and encountered the same problem... unfortunately all of my videos have a slate added at the head that kills even the _possibility_ of captions in the first 20 seconds, and of course I need to keep the timecode consistent, so I can't really run it pre-slating.  Is there a workaround for this nowadays?  I'd love to get off the MacCaption train! :)
Thanks!!

**Comment by dericed** [comment]
In the recent update there's a command line argument to specify how much time to search for captions. https://github.com/amiaopensource/sccyou/blob/23e5050ef4523329238c8c79b17fb9a008c41879/sccyou#L29-L39

I hope this works for you, else feel welcome to reopen the issue.
